# topics, topicTypes, port, and mode shoud be mirrors of one another
# topics: the names of the topics that the ros2relay will relay across network
# topicTypes: the full msg path of the topic 
#       NOTE: There is currently no support for custom types, only built in types
# port: port to communicate on
# server: remote server to connect to. 127.0.0.1 is localhost for local testing.
# num_listeners: number of threads spawned to handle incoming messages.
#       NOTE: depends on the number of topics being subscribed to, if you have
#           too few listeners, you may miss messages. However if you have too many you 
#           will tie up threads on your system.
ros2relay_net_publisher:
    ros__parameters:
        topics: ['camera/depth/camera_info',
            'camera/depth/color/points',
            'camera/depth/image_rect_raw',
            'tf_static']
        topicTypes: ['sensor_msgs.msg.CameraInfo',
            'sensor_msgs.msg.PointCloud2',
            'sensor_msgs.msg.Image',
            'tf2_msgs.msg.TFMessage']
        # priorities for each topic type - lower number = higher priority
        topicPriorities: [
            1,
            1,
            0,
            1
        ]
        port: 12499
        sampleRates: 40
        mode: 'tcp'
        server: "192.168.0.100"
        numWorkers: 40
ros2relay_net_subscriber:
    ros__parameters:
        topics: [
            'camera/aligned_depth_to_color/camera_info',
            'camera/aligned_depth_to_color/image_raw',
            'camera/color/camera_info',
            'camera/color/image_raw',
            'camera/depth/camera_info',
            'camera/depth/color/points',
            'camera/depth/image_rect_raw',
            'camera/infra1/camera_info',
            'camera/infra1/image_rect_raw',
            'camera/infra2/camera_info',
            'camera/infra2/image_rect_raw',
            'parameter_events',
            'tf_static']
        topicTypes: [
            'sensor_msgs.msg.CameraInfo',
            'sensor_msgs.msg.Image',
            'sensor_msgs.msg.CameraInfo',
            'sensor_msgs.msg.Image',
            'sensor_msgs.msg.CameraInfo',
            'sensor_msgs.msg.PointCloud2',
            'sensor_msgs.msg.Image',
            'sensor_msgs.msg.CameraInfo',
            'sensor_msgs.msg.Image',
            'sensor_msgs.msg.CameraInfo',
            'sensor_msgs.msg.Image',
            'rcl_interfaces.msg.ParameterEvent',
            'tf2_msgs.msg.TFMessage']
        mode: 'tcp'
        port: 12499
        # only applies to UDP
        num_listeners: 40
