# topics, topicTypes, port, and mode shoud be mirrors of one another
# topics: the names of the topics that the ros2relay will relay across network
# topicTypes: the full msg path of the topic 
#       NOTE: There is currently no support for custom types, only built in types
# port: port to communicate on
# server: remote server to connect to. 127.0.0.1 is localhost for local testing
# num_listeners: number of threads spawned to handle incoming messages.
#       NOTE: depends on the number of topics being subscribed to, if you have
#           too few listeners, you may miss messages. However if you have too many you 
#           will tie up threads on your system.
ros2relay_net_publisher:
    ros__parameters:
        topics: ['turtle1/cmd_vel']
        topicTypes: ['geometry_msgs.msg.Twist']
        port: 12499
        mode: "udp"
        server: 127.0.0.1
ros2relay_net_subscriber:
    ros__parameters:
        topics: ['turtle1/cmd_vel']
        topicTypes: ['geometry_msgs.msg.Twist']
        mode: "udp"
        port: 12499
        num_listeners: 5
